version: 2
updates:

  # Maintain dependencies for this gradle project
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      groups:
        junit:
          patterns:
            - "org.junit.vintage"
            - "org.junit.jupiter"
            - "junit"


  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
