name: Run tests

on:
  push:
    branches:
      - main
    paths:
      - '**.java'
      - 'build.gradle'
      - 'gradle/wrapper/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.java'
      - 'build.gradle'
      - 'gradle/wrapper/**'
#  schedule:
#    - cron: "0 */3 * * *"

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 21 ]
        os: [ubuntu, windows]
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run Gradle's test task
        run: ./gradlew --no-daemon --parallel --continue --build-cache --stacktrace test
  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: auto-merge
        if: |
          github.actor == 'dependabot[bot]' &&
          github.event_name == 'pull_request'
        run: |
          gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # this secret needs to be in the settings.secrets.dependabot
          GITHUB_TOKEN: ${{secrets.GH_ACTION_TOKEN}}
